name: ReleasePDFfile

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy files to another repository
        uses: lubu12/copy-files-to-repository@v1
        # Recall that you have to create (now it's created) a secret called API_TOKEN_GITHUB with a token with repo permissions and then you have to add it to the repository secrets. See the repository of lubu12 for more information.
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: victor-cv.pdf
          destination-username: victorballester7
          destination-repository: victorballester7.github.io
          destination-directory: assets/pdf
          commit-email: victor.ballester.ribo@gmail.com
          commit-message: "Update CV file"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload asset to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: victor-cv.pdf
          github-token: ${{ secrets.GITHUB_TOKEN }}
