name: ReleasePDFfile

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload asset to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: victor-cv.pdf
          github-token: ${{ secrets.GITHUB_TOKEN }}

  update:
    name: Update pdf in personal website
    runs-on: ubuntu-latest

    steps:
      - name: Commit and push changes
        run: |
          git clone https://github.com/victorballester7/victorballester7.github.io.git
          git clone https://github.com/victorballester7/cv.git
          ls
          cp https://github.com/victorballester7/CV/releases/latest/download/victor-cv.pdf victorballester7.github.io/assets/pdf/
          cd victorballester7.github.io
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish of CV"
          git push target master
