name: ReleasePDFfile

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Delete
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload asset to release
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          files: victor-cv.pdf
          github-token: ${{ secrets.GITHUB_TOKEN }}

  update:
    name: Update PDF in victorballester7.github.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cv repository
        uses: actions/checkout@v2
        with:
          repository: victorballester7/cv
      - name: Copy PDF to victorballester7.github.io repository
        run: |
          cp victor-cv.pdf ../victorballester7.github.io/tree/master/assets/pdf/
      - name: Checkout victorballester7.github.io repository
        uses: actions/checkout@v2
        with:
          repository: victorballester7/victorballester7.github.io
          path: victorballester7.github.io
      - name: Commit and push changes
        run: |
          cd victorballester7.github.io
          git config --local user.email "victor.ballester.ribo@gmail.com"
          git config --local user.name "victorballester7"
          git add assets/pdf/victor-cv.pdf
          git commit -m "Update CV PDF"
          git push
