name: ReleasePDFfile

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "victorCV_en.pdf"
          asset_name: "victorCV_en.pdf"
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my CV."
